// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHelmPluginVersionDetailsParams creates a new GetHelmPluginVersionDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHelmPluginVersionDetailsParams() *GetHelmPluginVersionDetailsParams {
	return &GetHelmPluginVersionDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHelmPluginVersionDetailsParamsWithTimeout creates a new GetHelmPluginVersionDetailsParams object
// with the ability to set a timeout on a request.
func NewGetHelmPluginVersionDetailsParamsWithTimeout(timeout time.Duration) *GetHelmPluginVersionDetailsParams {
	return &GetHelmPluginVersionDetailsParams{
		timeout: timeout,
	}
}

// NewGetHelmPluginVersionDetailsParamsWithContext creates a new GetHelmPluginVersionDetailsParams object
// with the ability to set a context for a request.
func NewGetHelmPluginVersionDetailsParamsWithContext(ctx context.Context) *GetHelmPluginVersionDetailsParams {
	return &GetHelmPluginVersionDetailsParams{
		Context: ctx,
	}
}

// NewGetHelmPluginVersionDetailsParamsWithHTTPClient creates a new GetHelmPluginVersionDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHelmPluginVersionDetailsParamsWithHTTPClient(client *http.Client) *GetHelmPluginVersionDetailsParams {
	return &GetHelmPluginVersionDetailsParams{
		HTTPClient: client,
	}
}

/*
GetHelmPluginVersionDetailsParams contains all the parameters to send to the API endpoint

	for the get helm plugin version details operation.

	Typically these are written to a http.Request.
*/
type GetHelmPluginVersionDetailsParams struct {

	/* PackageName.

	   Package name
	*/
	PackageName string

	/* RepoName.

	   Repository name
	*/
	RepoName string

	/* Version.

	   Package version
	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get helm plugin version details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHelmPluginVersionDetailsParams) WithDefaults() *GetHelmPluginVersionDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get helm plugin version details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHelmPluginVersionDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithTimeout(timeout time.Duration) *GetHelmPluginVersionDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithContext(ctx context.Context) *GetHelmPluginVersionDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithHTTPClient(client *http.Client) *GetHelmPluginVersionDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageName adds the packageName to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithPackageName(packageName string) *GetHelmPluginVersionDetailsParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithRepoName adds the repoName to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithRepoName(repoName string) *GetHelmPluginVersionDetailsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithVersion adds the version to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) WithVersion(version string) *GetHelmPluginVersionDetailsParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get helm plugin version details params
func (o *GetHelmPluginVersionDetailsParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetHelmPluginVersionDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
