// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// GetFalcoRulesDetailsReader is a Reader for the GetFalcoRulesDetails structure.
type GetFalcoRulesDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFalcoRulesDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFalcoRulesDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetFalcoRulesDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetFalcoRulesDetailsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetFalcoRulesDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFalcoRulesDetailsOK creates a GetFalcoRulesDetailsOK with default headers values
func NewGetFalcoRulesDetailsOK() *GetFalcoRulesDetailsOK {
	return &GetFalcoRulesDetailsOK{}
}

/*
GetFalcoRulesDetailsOK describes a response with status code 200, with default header values.

GetFalcoRulesDetailsOK get falco rules details o k
*/
type GetFalcoRulesDetailsOK struct {
	Payload *models.FalcoPackage
}

// IsSuccess returns true when this get falco rules details o k response has a 2xx status code
func (o *GetFalcoRulesDetailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get falco rules details o k response has a 3xx status code
func (o *GetFalcoRulesDetailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get falco rules details o k response has a 4xx status code
func (o *GetFalcoRulesDetailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get falco rules details o k response has a 5xx status code
func (o *GetFalcoRulesDetailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get falco rules details o k response a status code equal to that given
func (o *GetFalcoRulesDetailsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetFalcoRulesDetailsOK) Error() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsOK  %+v", 200, o.Payload)
}

func (o *GetFalcoRulesDetailsOK) String() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsOK  %+v", 200, o.Payload)
}

func (o *GetFalcoRulesDetailsOK) GetPayload() *models.FalcoPackage {
	return o.Payload
}

func (o *GetFalcoRulesDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FalcoPackage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFalcoRulesDetailsNotFound creates a GetFalcoRulesDetailsNotFound with default headers values
func NewGetFalcoRulesDetailsNotFound() *GetFalcoRulesDetailsNotFound {
	return &GetFalcoRulesDetailsNotFound{}
}

/*
GetFalcoRulesDetailsNotFound describes a response with status code 404, with default header values.

The requested resource was not found
*/
type GetFalcoRulesDetailsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get falco rules details not found response has a 2xx status code
func (o *GetFalcoRulesDetailsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get falco rules details not found response has a 3xx status code
func (o *GetFalcoRulesDetailsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get falco rules details not found response has a 4xx status code
func (o *GetFalcoRulesDetailsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get falco rules details not found response has a 5xx status code
func (o *GetFalcoRulesDetailsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get falco rules details not found response a status code equal to that given
func (o *GetFalcoRulesDetailsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetFalcoRulesDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsNotFound  %+v", 404, o.Payload)
}

func (o *GetFalcoRulesDetailsNotFound) String() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsNotFound  %+v", 404, o.Payload)
}

func (o *GetFalcoRulesDetailsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetFalcoRulesDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFalcoRulesDetailsTooManyRequests creates a GetFalcoRulesDetailsTooManyRequests with default headers values
func NewGetFalcoRulesDetailsTooManyRequests() *GetFalcoRulesDetailsTooManyRequests {
	return &GetFalcoRulesDetailsTooManyRequests{}
}

/*
GetFalcoRulesDetailsTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type GetFalcoRulesDetailsTooManyRequests struct {
}

// IsSuccess returns true when this get falco rules details too many requests response has a 2xx status code
func (o *GetFalcoRulesDetailsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get falco rules details too many requests response has a 3xx status code
func (o *GetFalcoRulesDetailsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get falco rules details too many requests response has a 4xx status code
func (o *GetFalcoRulesDetailsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get falco rules details too many requests response has a 5xx status code
func (o *GetFalcoRulesDetailsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get falco rules details too many requests response a status code equal to that given
func (o *GetFalcoRulesDetailsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetFalcoRulesDetailsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsTooManyRequests ", 429)
}

func (o *GetFalcoRulesDetailsTooManyRequests) String() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsTooManyRequests ", 429)
}

func (o *GetFalcoRulesDetailsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFalcoRulesDetailsInternalServerError creates a GetFalcoRulesDetailsInternalServerError with default headers values
func NewGetFalcoRulesDetailsInternalServerError() *GetFalcoRulesDetailsInternalServerError {
	return &GetFalcoRulesDetailsInternalServerError{}
}

/*
GetFalcoRulesDetailsInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type GetFalcoRulesDetailsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get falco rules details internal server error response has a 2xx status code
func (o *GetFalcoRulesDetailsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get falco rules details internal server error response has a 3xx status code
func (o *GetFalcoRulesDetailsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get falco rules details internal server error response has a 4xx status code
func (o *GetFalcoRulesDetailsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get falco rules details internal server error response has a 5xx status code
func (o *GetFalcoRulesDetailsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get falco rules details internal server error response a status code equal to that given
func (o *GetFalcoRulesDetailsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetFalcoRulesDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFalcoRulesDetailsInternalServerError) String() string {
	return fmt.Sprintf("[GET /packages/falco/{repoName}/{packageName}][%d] getFalcoRulesDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFalcoRulesDetailsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetFalcoRulesDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
