// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// GetKnativeClientPluginsVersionDetailsReader is a Reader for the GetKnativeClientPluginsVersionDetails structure.
type GetKnativeClientPluginsVersionDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKnativeClientPluginsVersionDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKnativeClientPluginsVersionDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetKnativeClientPluginsVersionDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetKnativeClientPluginsVersionDetailsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetKnativeClientPluginsVersionDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetKnativeClientPluginsVersionDetailsOK creates a GetKnativeClientPluginsVersionDetailsOK with default headers values
func NewGetKnativeClientPluginsVersionDetailsOK() *GetKnativeClientPluginsVersionDetailsOK {
	return &GetKnativeClientPluginsVersionDetailsOK{}
}

/*
GetKnativeClientPluginsVersionDetailsOK describes a response with status code 200, with default header values.

GetKnativeClientPluginsVersionDetailsOK get knative client plugins version details o k
*/
type GetKnativeClientPluginsVersionDetailsOK struct {
	Payload *models.KnativeClientPluginsPackage
}

// IsSuccess returns true when this get knative client plugins version details o k response has a 2xx status code
func (o *GetKnativeClientPluginsVersionDetailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get knative client plugins version details o k response has a 3xx status code
func (o *GetKnativeClientPluginsVersionDetailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get knative client plugins version details o k response has a 4xx status code
func (o *GetKnativeClientPluginsVersionDetailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get knative client plugins version details o k response has a 5xx status code
func (o *GetKnativeClientPluginsVersionDetailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get knative client plugins version details o k response a status code equal to that given
func (o *GetKnativeClientPluginsVersionDetailsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetKnativeClientPluginsVersionDetailsOK) Error() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsOK  %+v", 200, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsOK) String() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsOK  %+v", 200, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsOK) GetPayload() *models.KnativeClientPluginsPackage {
	return o.Payload
}

func (o *GetKnativeClientPluginsVersionDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KnativeClientPluginsPackage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKnativeClientPluginsVersionDetailsNotFound creates a GetKnativeClientPluginsVersionDetailsNotFound with default headers values
func NewGetKnativeClientPluginsVersionDetailsNotFound() *GetKnativeClientPluginsVersionDetailsNotFound {
	return &GetKnativeClientPluginsVersionDetailsNotFound{}
}

/*
GetKnativeClientPluginsVersionDetailsNotFound describes a response with status code 404, with default header values.

The requested resource was not found
*/
type GetKnativeClientPluginsVersionDetailsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get knative client plugins version details not found response has a 2xx status code
func (o *GetKnativeClientPluginsVersionDetailsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get knative client plugins version details not found response has a 3xx status code
func (o *GetKnativeClientPluginsVersionDetailsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get knative client plugins version details not found response has a 4xx status code
func (o *GetKnativeClientPluginsVersionDetailsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get knative client plugins version details not found response has a 5xx status code
func (o *GetKnativeClientPluginsVersionDetailsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get knative client plugins version details not found response a status code equal to that given
func (o *GetKnativeClientPluginsVersionDetailsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetKnativeClientPluginsVersionDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsNotFound  %+v", 404, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsNotFound) String() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsNotFound  %+v", 404, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetKnativeClientPluginsVersionDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKnativeClientPluginsVersionDetailsTooManyRequests creates a GetKnativeClientPluginsVersionDetailsTooManyRequests with default headers values
func NewGetKnativeClientPluginsVersionDetailsTooManyRequests() *GetKnativeClientPluginsVersionDetailsTooManyRequests {
	return &GetKnativeClientPluginsVersionDetailsTooManyRequests{}
}

/*
GetKnativeClientPluginsVersionDetailsTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type GetKnativeClientPluginsVersionDetailsTooManyRequests struct {
}

// IsSuccess returns true when this get knative client plugins version details too many requests response has a 2xx status code
func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get knative client plugins version details too many requests response has a 3xx status code
func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get knative client plugins version details too many requests response has a 4xx status code
func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get knative client plugins version details too many requests response has a 5xx status code
func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get knative client plugins version details too many requests response a status code equal to that given
func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsTooManyRequests ", 429)
}

func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) String() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsTooManyRequests ", 429)
}

func (o *GetKnativeClientPluginsVersionDetailsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetKnativeClientPluginsVersionDetailsInternalServerError creates a GetKnativeClientPluginsVersionDetailsInternalServerError with default headers values
func NewGetKnativeClientPluginsVersionDetailsInternalServerError() *GetKnativeClientPluginsVersionDetailsInternalServerError {
	return &GetKnativeClientPluginsVersionDetailsInternalServerError{}
}

/*
GetKnativeClientPluginsVersionDetailsInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type GetKnativeClientPluginsVersionDetailsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get knative client plugins version details internal server error response has a 2xx status code
func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get knative client plugins version details internal server error response has a 3xx status code
func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get knative client plugins version details internal server error response has a 4xx status code
func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get knative client plugins version details internal server error response has a 5xx status code
func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get knative client plugins version details internal server error response a status code equal to that given
func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) String() string {
	return fmt.Sprintf("[GET /packages/knative-client-plugin/{repoName}/{packageName}/{version}][%d] getKnativeClientPluginsVersionDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetKnativeClientPluginsVersionDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
