// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKedaScalerDetailsParams creates a new GetKedaScalerDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetKedaScalerDetailsParams() *GetKedaScalerDetailsParams {
	return &GetKedaScalerDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetKedaScalerDetailsParamsWithTimeout creates a new GetKedaScalerDetailsParams object
// with the ability to set a timeout on a request.
func NewGetKedaScalerDetailsParamsWithTimeout(timeout time.Duration) *GetKedaScalerDetailsParams {
	return &GetKedaScalerDetailsParams{
		timeout: timeout,
	}
}

// NewGetKedaScalerDetailsParamsWithContext creates a new GetKedaScalerDetailsParams object
// with the ability to set a context for a request.
func NewGetKedaScalerDetailsParamsWithContext(ctx context.Context) *GetKedaScalerDetailsParams {
	return &GetKedaScalerDetailsParams{
		Context: ctx,
	}
}

// NewGetKedaScalerDetailsParamsWithHTTPClient creates a new GetKedaScalerDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetKedaScalerDetailsParamsWithHTTPClient(client *http.Client) *GetKedaScalerDetailsParams {
	return &GetKedaScalerDetailsParams{
		HTTPClient: client,
	}
}

/*
GetKedaScalerDetailsParams contains all the parameters to send to the API endpoint

	for the get keda scaler details operation.

	Typically these are written to a http.Request.
*/
type GetKedaScalerDetailsParams struct {

	/* PackageName.

	   Package name
	*/
	PackageName string

	/* RepoName.

	   Repository name
	*/
	RepoName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get keda scaler details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKedaScalerDetailsParams) WithDefaults() *GetKedaScalerDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get keda scaler details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKedaScalerDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) WithTimeout(timeout time.Duration) *GetKedaScalerDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) WithContext(ctx context.Context) *GetKedaScalerDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) WithHTTPClient(client *http.Client) *GetKedaScalerDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageName adds the packageName to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) WithPackageName(packageName string) *GetKedaScalerDetailsParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithRepoName adds the repoName to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) WithRepoName(repoName string) *GetKedaScalerDetailsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get keda scaler details params
func (o *GetKedaScalerDetailsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WriteToRequest writes these params to a swagger request
func (o *GetKedaScalerDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
