// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKedaScalerVersionDetailsParams creates a new GetKedaScalerVersionDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetKedaScalerVersionDetailsParams() *GetKedaScalerVersionDetailsParams {
	return &GetKedaScalerVersionDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetKedaScalerVersionDetailsParamsWithTimeout creates a new GetKedaScalerVersionDetailsParams object
// with the ability to set a timeout on a request.
func NewGetKedaScalerVersionDetailsParamsWithTimeout(timeout time.Duration) *GetKedaScalerVersionDetailsParams {
	return &GetKedaScalerVersionDetailsParams{
		timeout: timeout,
	}
}

// NewGetKedaScalerVersionDetailsParamsWithContext creates a new GetKedaScalerVersionDetailsParams object
// with the ability to set a context for a request.
func NewGetKedaScalerVersionDetailsParamsWithContext(ctx context.Context) *GetKedaScalerVersionDetailsParams {
	return &GetKedaScalerVersionDetailsParams{
		Context: ctx,
	}
}

// NewGetKedaScalerVersionDetailsParamsWithHTTPClient creates a new GetKedaScalerVersionDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetKedaScalerVersionDetailsParamsWithHTTPClient(client *http.Client) *GetKedaScalerVersionDetailsParams {
	return &GetKedaScalerVersionDetailsParams{
		HTTPClient: client,
	}
}

/*
GetKedaScalerVersionDetailsParams contains all the parameters to send to the API endpoint

	for the get keda scaler version details operation.

	Typically these are written to a http.Request.
*/
type GetKedaScalerVersionDetailsParams struct {

	/* PackageName.

	   Package name
	*/
	PackageName string

	/* RepoName.

	   Repository name
	*/
	RepoName string

	/* Version.

	   Package version
	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get keda scaler version details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKedaScalerVersionDetailsParams) WithDefaults() *GetKedaScalerVersionDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get keda scaler version details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKedaScalerVersionDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithTimeout(timeout time.Duration) *GetKedaScalerVersionDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithContext(ctx context.Context) *GetKedaScalerVersionDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithHTTPClient(client *http.Client) *GetKedaScalerVersionDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageName adds the packageName to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithPackageName(packageName string) *GetKedaScalerVersionDetailsParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithRepoName adds the repoName to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithRepoName(repoName string) *GetKedaScalerVersionDetailsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithVersion adds the version to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) WithVersion(version string) *GetKedaScalerVersionDetailsParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get keda scaler version details params
func (o *GetKedaScalerVersionDetailsParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetKedaScalerVersionDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
