// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFalcoRulesDetailsParams creates a new GetFalcoRulesDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFalcoRulesDetailsParams() *GetFalcoRulesDetailsParams {
	return &GetFalcoRulesDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFalcoRulesDetailsParamsWithTimeout creates a new GetFalcoRulesDetailsParams object
// with the ability to set a timeout on a request.
func NewGetFalcoRulesDetailsParamsWithTimeout(timeout time.Duration) *GetFalcoRulesDetailsParams {
	return &GetFalcoRulesDetailsParams{
		timeout: timeout,
	}
}

// NewGetFalcoRulesDetailsParamsWithContext creates a new GetFalcoRulesDetailsParams object
// with the ability to set a context for a request.
func NewGetFalcoRulesDetailsParamsWithContext(ctx context.Context) *GetFalcoRulesDetailsParams {
	return &GetFalcoRulesDetailsParams{
		Context: ctx,
	}
}

// NewGetFalcoRulesDetailsParamsWithHTTPClient creates a new GetFalcoRulesDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFalcoRulesDetailsParamsWithHTTPClient(client *http.Client) *GetFalcoRulesDetailsParams {
	return &GetFalcoRulesDetailsParams{
		HTTPClient: client,
	}
}

/*
GetFalcoRulesDetailsParams contains all the parameters to send to the API endpoint

	for the get falco rules details operation.

	Typically these are written to a http.Request.
*/
type GetFalcoRulesDetailsParams struct {

	/* PackageName.

	   Package name
	*/
	PackageName string

	/* RepoName.

	   Repository name
	*/
	RepoName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get falco rules details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFalcoRulesDetailsParams) WithDefaults() *GetFalcoRulesDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get falco rules details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFalcoRulesDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) WithTimeout(timeout time.Duration) *GetFalcoRulesDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) WithContext(ctx context.Context) *GetFalcoRulesDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) WithHTTPClient(client *http.Client) *GetFalcoRulesDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageName adds the packageName to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) WithPackageName(packageName string) *GetFalcoRulesDetailsParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithRepoName adds the repoName to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) WithRepoName(repoName string) *GetFalcoRulesDetailsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get falco rules details params
func (o *GetFalcoRulesDetailsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WriteToRequest writes these params to a swagger request
func (o *GetFalcoRulesDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
