// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// GetChartValuesReader is a Reader for the GetChartValues structure.
type GetChartValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetChartValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetChartValuesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetChartValuesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetChartValuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetChartValuesOK creates a GetChartValuesOK with default headers values
func NewGetChartValuesOK() *GetChartValuesOK {
	return &GetChartValuesOK{}
}

/*
GetChartValuesOK describes a response with status code 200, with default header values.

GetChartValuesOK get chart values o k
*/
type GetChartValuesOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get chart values o k response has a 2xx status code
func (o *GetChartValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get chart values o k response has a 3xx status code
func (o *GetChartValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chart values o k response has a 4xx status code
func (o *GetChartValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get chart values o k response has a 5xx status code
func (o *GetChartValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get chart values o k response a status code equal to that given
func (o *GetChartValuesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetChartValuesOK) Error() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesOK  %+v", 200, o.Payload)
}

func (o *GetChartValuesOK) String() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesOK  %+v", 200, o.Payload)
}

func (o *GetChartValuesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetChartValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartValuesNotFound creates a GetChartValuesNotFound with default headers values
func NewGetChartValuesNotFound() *GetChartValuesNotFound {
	return &GetChartValuesNotFound{}
}

/*
GetChartValuesNotFound describes a response with status code 404, with default header values.

The requested resource was not found
*/
type GetChartValuesNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get chart values not found response has a 2xx status code
func (o *GetChartValuesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get chart values not found response has a 3xx status code
func (o *GetChartValuesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chart values not found response has a 4xx status code
func (o *GetChartValuesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get chart values not found response has a 5xx status code
func (o *GetChartValuesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get chart values not found response a status code equal to that given
func (o *GetChartValuesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetChartValuesNotFound) Error() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesNotFound  %+v", 404, o.Payload)
}

func (o *GetChartValuesNotFound) String() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesNotFound  %+v", 404, o.Payload)
}

func (o *GetChartValuesNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetChartValuesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartValuesTooManyRequests creates a GetChartValuesTooManyRequests with default headers values
func NewGetChartValuesTooManyRequests() *GetChartValuesTooManyRequests {
	return &GetChartValuesTooManyRequests{}
}

/*
GetChartValuesTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type GetChartValuesTooManyRequests struct {
}

// IsSuccess returns true when this get chart values too many requests response has a 2xx status code
func (o *GetChartValuesTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get chart values too many requests response has a 3xx status code
func (o *GetChartValuesTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chart values too many requests response has a 4xx status code
func (o *GetChartValuesTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get chart values too many requests response has a 5xx status code
func (o *GetChartValuesTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get chart values too many requests response a status code equal to that given
func (o *GetChartValuesTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetChartValuesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesTooManyRequests ", 429)
}

func (o *GetChartValuesTooManyRequests) String() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesTooManyRequests ", 429)
}

func (o *GetChartValuesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartValuesInternalServerError creates a GetChartValuesInternalServerError with default headers values
func NewGetChartValuesInternalServerError() *GetChartValuesInternalServerError {
	return &GetChartValuesInternalServerError{}
}

/*
GetChartValuesInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type GetChartValuesInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get chart values internal server error response has a 2xx status code
func (o *GetChartValuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get chart values internal server error response has a 3xx status code
func (o *GetChartValuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chart values internal server error response has a 4xx status code
func (o *GetChartValuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get chart values internal server error response has a 5xx status code
func (o *GetChartValuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get chart values internal server error response a status code equal to that given
func (o *GetChartValuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetChartValuesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetChartValuesInternalServerError) String() string {
	return fmt.Sprintf("[GET /packages/{packageID}/{version}/values][%d] getChartValuesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetChartValuesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetChartValuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
