// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTektonPipelineDetailsParams creates a new GetTektonPipelineDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTektonPipelineDetailsParams() *GetTektonPipelineDetailsParams {
	return &GetTektonPipelineDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTektonPipelineDetailsParamsWithTimeout creates a new GetTektonPipelineDetailsParams object
// with the ability to set a timeout on a request.
func NewGetTektonPipelineDetailsParamsWithTimeout(timeout time.Duration) *GetTektonPipelineDetailsParams {
	return &GetTektonPipelineDetailsParams{
		timeout: timeout,
	}
}

// NewGetTektonPipelineDetailsParamsWithContext creates a new GetTektonPipelineDetailsParams object
// with the ability to set a context for a request.
func NewGetTektonPipelineDetailsParamsWithContext(ctx context.Context) *GetTektonPipelineDetailsParams {
	return &GetTektonPipelineDetailsParams{
		Context: ctx,
	}
}

// NewGetTektonPipelineDetailsParamsWithHTTPClient creates a new GetTektonPipelineDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTektonPipelineDetailsParamsWithHTTPClient(client *http.Client) *GetTektonPipelineDetailsParams {
	return &GetTektonPipelineDetailsParams{
		HTTPClient: client,
	}
}

/*
GetTektonPipelineDetailsParams contains all the parameters to send to the API endpoint

	for the get tekton pipeline details operation.

	Typically these are written to a http.Request.
*/
type GetTektonPipelineDetailsParams struct {

	/* PackageName.

	   Package name
	*/
	PackageName string

	/* RepoName.

	   Repository name
	*/
	RepoName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tekton pipeline details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineDetailsParams) WithDefaults() *GetTektonPipelineDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tekton pipeline details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) WithTimeout(timeout time.Duration) *GetTektonPipelineDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) WithContext(ctx context.Context) *GetTektonPipelineDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) WithHTTPClient(client *http.Client) *GetTektonPipelineDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageName adds the packageName to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) WithPackageName(packageName string) *GetTektonPipelineDetailsParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithRepoName adds the repoName to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) WithRepoName(repoName string) *GetTektonPipelineDetailsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get tekton pipeline details params
func (o *GetTektonPipelineDetailsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTektonPipelineDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
