// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// GetPackageSummaryReader is a Reader for the GetPackageSummary structure.
type GetPackageSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPackageSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPackageSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetPackageSummaryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetPackageSummaryTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPackageSummaryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPackageSummaryOK creates a GetPackageSummaryOK with default headers values
func NewGetPackageSummaryOK() *GetPackageSummaryOK {
	return &GetPackageSummaryOK{}
}

/*
GetPackageSummaryOK describes a response with status code 200, with default header values.

GetPackageSummaryOK get package summary o k
*/
type GetPackageSummaryOK struct {
	Payload *models.PackageSummary
}

// IsSuccess returns true when this get package summary o k response has a 2xx status code
func (o *GetPackageSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get package summary o k response has a 3xx status code
func (o *GetPackageSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get package summary o k response has a 4xx status code
func (o *GetPackageSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get package summary o k response has a 5xx status code
func (o *GetPackageSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get package summary o k response a status code equal to that given
func (o *GetPackageSummaryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetPackageSummaryOK) Error() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryOK  %+v", 200, o.Payload)
}

func (o *GetPackageSummaryOK) String() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryOK  %+v", 200, o.Payload)
}

func (o *GetPackageSummaryOK) GetPayload() *models.PackageSummary {
	return o.Payload
}

func (o *GetPackageSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PackageSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPackageSummaryNotFound creates a GetPackageSummaryNotFound with default headers values
func NewGetPackageSummaryNotFound() *GetPackageSummaryNotFound {
	return &GetPackageSummaryNotFound{}
}

/*
GetPackageSummaryNotFound describes a response with status code 404, with default header values.

The requested resource was not found
*/
type GetPackageSummaryNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get package summary not found response has a 2xx status code
func (o *GetPackageSummaryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get package summary not found response has a 3xx status code
func (o *GetPackageSummaryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get package summary not found response has a 4xx status code
func (o *GetPackageSummaryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get package summary not found response has a 5xx status code
func (o *GetPackageSummaryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get package summary not found response a status code equal to that given
func (o *GetPackageSummaryNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetPackageSummaryNotFound) Error() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryNotFound  %+v", 404, o.Payload)
}

func (o *GetPackageSummaryNotFound) String() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryNotFound  %+v", 404, o.Payload)
}

func (o *GetPackageSummaryNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPackageSummaryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPackageSummaryTooManyRequests creates a GetPackageSummaryTooManyRequests with default headers values
func NewGetPackageSummaryTooManyRequests() *GetPackageSummaryTooManyRequests {
	return &GetPackageSummaryTooManyRequests{}
}

/*
GetPackageSummaryTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type GetPackageSummaryTooManyRequests struct {
}

// IsSuccess returns true when this get package summary too many requests response has a 2xx status code
func (o *GetPackageSummaryTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get package summary too many requests response has a 3xx status code
func (o *GetPackageSummaryTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get package summary too many requests response has a 4xx status code
func (o *GetPackageSummaryTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get package summary too many requests response has a 5xx status code
func (o *GetPackageSummaryTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get package summary too many requests response a status code equal to that given
func (o *GetPackageSummaryTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetPackageSummaryTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryTooManyRequests ", 429)
}

func (o *GetPackageSummaryTooManyRequests) String() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryTooManyRequests ", 429)
}

func (o *GetPackageSummaryTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPackageSummaryInternalServerError creates a GetPackageSummaryInternalServerError with default headers values
func NewGetPackageSummaryInternalServerError() *GetPackageSummaryInternalServerError {
	return &GetPackageSummaryInternalServerError{}
}

/*
GetPackageSummaryInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type GetPackageSummaryInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get package summary internal server error response has a 2xx status code
func (o *GetPackageSummaryInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get package summary internal server error response has a 3xx status code
func (o *GetPackageSummaryInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get package summary internal server error response has a 4xx status code
func (o *GetPackageSummaryInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get package summary internal server error response has a 5xx status code
func (o *GetPackageSummaryInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get package summary internal server error response a status code equal to that given
func (o *GetPackageSummaryInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetPackageSummaryInternalServerError) Error() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPackageSummaryInternalServerError) String() string {
	return fmt.Sprintf("[GET /packages/{repoKindParam}/{repoName}/{packageName}/summary][%d] getPackageSummaryInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPackageSummaryInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPackageSummaryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
