// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// NewAddOrganizationWebhookParams creates a new AddOrganizationWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddOrganizationWebhookParams() *AddOrganizationWebhookParams {
	return &AddOrganizationWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddOrganizationWebhookParamsWithTimeout creates a new AddOrganizationWebhookParams object
// with the ability to set a timeout on a request.
func NewAddOrganizationWebhookParamsWithTimeout(timeout time.Duration) *AddOrganizationWebhookParams {
	return &AddOrganizationWebhookParams{
		timeout: timeout,
	}
}

// NewAddOrganizationWebhookParamsWithContext creates a new AddOrganizationWebhookParams object
// with the ability to set a context for a request.
func NewAddOrganizationWebhookParamsWithContext(ctx context.Context) *AddOrganizationWebhookParams {
	return &AddOrganizationWebhookParams{
		Context: ctx,
	}
}

// NewAddOrganizationWebhookParamsWithHTTPClient creates a new AddOrganizationWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddOrganizationWebhookParamsWithHTTPClient(client *http.Client) *AddOrganizationWebhookParams {
	return &AddOrganizationWebhookParams{
		HTTPClient: client,
	}
}

/*
AddOrganizationWebhookParams contains all the parameters to send to the API endpoint

	for the add organization webhook operation.

	Typically these are written to a http.Request.
*/
type AddOrganizationWebhookParams struct {

	// ContentType.
	ContentType *string

	/* Body.

	   Webhook body
	*/
	Body *models.WebhookSummaryWithPackages

	/* OrgName.

	   Organization name
	*/
	OrgName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add organization webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddOrganizationWebhookParams) WithDefaults() *AddOrganizationWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add organization webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddOrganizationWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithTimeout(timeout time.Duration) *AddOrganizationWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithContext(ctx context.Context) *AddOrganizationWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithHTTPClient(client *http.Client) *AddOrganizationWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithContentType(contentType *string) *AddOrganizationWebhookParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithBody(body *models.WebhookSummaryWithPackages) *AddOrganizationWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetBody(body *models.WebhookSummaryWithPackages) {
	o.Body = body
}

// WithOrgName adds the orgName to the add organization webhook params
func (o *AddOrganizationWebhookParams) WithOrgName(orgName string) *AddOrganizationWebhookParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the add organization webhook params
func (o *AddOrganizationWebhookParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WriteToRequest writes these params to a swagger request
func (o *AddOrganizationWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
