// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// GetOrganizationWebhooksReader is a Reader for the GetOrganizationWebhooks structure.
type GetOrganizationWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetOrganizationWebhooksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetOrganizationWebhooksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOrganizationWebhooksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationWebhooksOK creates a GetOrganizationWebhooksOK with default headers values
func NewGetOrganizationWebhooksOK() *GetOrganizationWebhooksOK {
	return &GetOrganizationWebhooksOK{}
}

/*
GetOrganizationWebhooksOK describes a response with status code 200, with default header values.

GetOrganizationWebhooksOK get organization webhooks o k
*/
type GetOrganizationWebhooksOK struct {

	/* Total number of organization's webhooks
	 */
	PaginationTotalCount string

	Payload []*models.Webhook
}

// IsSuccess returns true when this get organization webhooks o k response has a 2xx status code
func (o *GetOrganizationWebhooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization webhooks o k response has a 3xx status code
func (o *GetOrganizationWebhooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization webhooks o k response has a 4xx status code
func (o *GetOrganizationWebhooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization webhooks o k response has a 5xx status code
func (o *GetOrganizationWebhooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization webhooks o k response a status code equal to that given
func (o *GetOrganizationWebhooksOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOrganizationWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationWebhooksOK) String() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationWebhooksOK) GetPayload() []*models.Webhook {
	return o.Payload
}

func (o *GetOrganizationWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Pagination-Total-Count
	hdrPaginationTotalCount := response.GetHeader("Pagination-Total-Count")

	if hdrPaginationTotalCount != "" {
		o.PaginationTotalCount = hdrPaginationTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationWebhooksUnauthorized creates a GetOrganizationWebhooksUnauthorized with default headers values
func NewGetOrganizationWebhooksUnauthorized() *GetOrganizationWebhooksUnauthorized {
	return &GetOrganizationWebhooksUnauthorized{}
}

/*
GetOrganizationWebhooksUnauthorized describes a response with status code 401, with default header values.

Valid authentication credentials not provided
*/
type GetOrganizationWebhooksUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get organization webhooks unauthorized response has a 2xx status code
func (o *GetOrganizationWebhooksUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization webhooks unauthorized response has a 3xx status code
func (o *GetOrganizationWebhooksUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization webhooks unauthorized response has a 4xx status code
func (o *GetOrganizationWebhooksUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization webhooks unauthorized response has a 5xx status code
func (o *GetOrganizationWebhooksUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization webhooks unauthorized response a status code equal to that given
func (o *GetOrganizationWebhooksUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetOrganizationWebhooksUnauthorized) Error() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksUnauthorized  %+v", 401, o.Payload)
}

func (o *GetOrganizationWebhooksUnauthorized) String() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksUnauthorized  %+v", 401, o.Payload)
}

func (o *GetOrganizationWebhooksUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOrganizationWebhooksUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationWebhooksTooManyRequests creates a GetOrganizationWebhooksTooManyRequests with default headers values
func NewGetOrganizationWebhooksTooManyRequests() *GetOrganizationWebhooksTooManyRequests {
	return &GetOrganizationWebhooksTooManyRequests{}
}

/*
GetOrganizationWebhooksTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type GetOrganizationWebhooksTooManyRequests struct {
}

// IsSuccess returns true when this get organization webhooks too many requests response has a 2xx status code
func (o *GetOrganizationWebhooksTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization webhooks too many requests response has a 3xx status code
func (o *GetOrganizationWebhooksTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization webhooks too many requests response has a 4xx status code
func (o *GetOrganizationWebhooksTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization webhooks too many requests response has a 5xx status code
func (o *GetOrganizationWebhooksTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization webhooks too many requests response a status code equal to that given
func (o *GetOrganizationWebhooksTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetOrganizationWebhooksTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksTooManyRequests ", 429)
}

func (o *GetOrganizationWebhooksTooManyRequests) String() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksTooManyRequests ", 429)
}

func (o *GetOrganizationWebhooksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationWebhooksInternalServerError creates a GetOrganizationWebhooksInternalServerError with default headers values
func NewGetOrganizationWebhooksInternalServerError() *GetOrganizationWebhooksInternalServerError {
	return &GetOrganizationWebhooksInternalServerError{}
}

/*
GetOrganizationWebhooksInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type GetOrganizationWebhooksInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get organization webhooks internal server error response has a 2xx status code
func (o *GetOrganizationWebhooksInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization webhooks internal server error response has a 3xx status code
func (o *GetOrganizationWebhooksInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization webhooks internal server error response has a 4xx status code
func (o *GetOrganizationWebhooksInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization webhooks internal server error response has a 5xx status code
func (o *GetOrganizationWebhooksInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get organization webhooks internal server error response a status code equal to that given
func (o *GetOrganizationWebhooksInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetOrganizationWebhooksInternalServerError) Error() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksInternalServerError  %+v", 500, o.Payload)
}

func (o *GetOrganizationWebhooksInternalServerError) String() string {
	return fmt.Sprintf("[GET /webhooks/org/{orgName}][%d] getOrganizationWebhooksInternalServerError  %+v", 500, o.Payload)
}

func (o *GetOrganizationWebhooksInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOrganizationWebhooksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
