// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// NewUpdateOrganizationWebhookParams creates a new UpdateOrganizationWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOrganizationWebhookParams() *UpdateOrganizationWebhookParams {
	return &UpdateOrganizationWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOrganizationWebhookParamsWithTimeout creates a new UpdateOrganizationWebhookParams object
// with the ability to set a timeout on a request.
func NewUpdateOrganizationWebhookParamsWithTimeout(timeout time.Duration) *UpdateOrganizationWebhookParams {
	return &UpdateOrganizationWebhookParams{
		timeout: timeout,
	}
}

// NewUpdateOrganizationWebhookParamsWithContext creates a new UpdateOrganizationWebhookParams object
// with the ability to set a context for a request.
func NewUpdateOrganizationWebhookParamsWithContext(ctx context.Context) *UpdateOrganizationWebhookParams {
	return &UpdateOrganizationWebhookParams{
		Context: ctx,
	}
}

// NewUpdateOrganizationWebhookParamsWithHTTPClient creates a new UpdateOrganizationWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOrganizationWebhookParamsWithHTTPClient(client *http.Client) *UpdateOrganizationWebhookParams {
	return &UpdateOrganizationWebhookParams{
		HTTPClient: client,
	}
}

/*
UpdateOrganizationWebhookParams contains all the parameters to send to the API endpoint

	for the update organization webhook operation.

	Typically these are written to a http.Request.
*/
type UpdateOrganizationWebhookParams struct {

	// ContentType.
	ContentType *string

	/* Body.

	   Webhook body
	*/
	Body *models.WebhookSummaryWithPackages

	/* OrgName.

	   Organization name
	*/
	OrgName string

	/* WebhookID.

	   Webhook ID

	   Format: uuid
	*/
	WebhookID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update organization webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrganizationWebhookParams) WithDefaults() *UpdateOrganizationWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update organization webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrganizationWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithTimeout(timeout time.Duration) *UpdateOrganizationWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithContext(ctx context.Context) *UpdateOrganizationWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithHTTPClient(client *http.Client) *UpdateOrganizationWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithContentType(contentType *string) *UpdateOrganizationWebhookParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithBody(body *models.WebhookSummaryWithPackages) *UpdateOrganizationWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetBody(body *models.WebhookSummaryWithPackages) {
	o.Body = body
}

// WithOrgName adds the orgName to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithOrgName(orgName string) *UpdateOrganizationWebhookParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithWebhookID adds the webhookID to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) WithWebhookID(webhookID strfmt.UUID) *UpdateOrganizationWebhookParams {
	o.SetWebhookID(webhookID)
	return o
}

// SetWebhookID adds the webhookId to the update organization webhook params
func (o *UpdateOrganizationWebhookParams) SetWebhookID(webhookID strfmt.UUID) {
	o.WebhookID = webhookID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOrganizationWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param webhookID
	if err := r.SetPathParam("webhookID", o.WebhookID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
