// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// NewAddPackageSubscriptionParams creates a new AddPackageSubscriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddPackageSubscriptionParams() *AddPackageSubscriptionParams {
	return &AddPackageSubscriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddPackageSubscriptionParamsWithTimeout creates a new AddPackageSubscriptionParams object
// with the ability to set a timeout on a request.
func NewAddPackageSubscriptionParamsWithTimeout(timeout time.Duration) *AddPackageSubscriptionParams {
	return &AddPackageSubscriptionParams{
		timeout: timeout,
	}
}

// NewAddPackageSubscriptionParamsWithContext creates a new AddPackageSubscriptionParams object
// with the ability to set a context for a request.
func NewAddPackageSubscriptionParamsWithContext(ctx context.Context) *AddPackageSubscriptionParams {
	return &AddPackageSubscriptionParams{
		Context: ctx,
	}
}

// NewAddPackageSubscriptionParamsWithHTTPClient creates a new AddPackageSubscriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddPackageSubscriptionParamsWithHTTPClient(client *http.Client) *AddPackageSubscriptionParams {
	return &AddPackageSubscriptionParams{
		HTTPClient: client,
	}
}

/*
AddPackageSubscriptionParams contains all the parameters to send to the API endpoint

	for the add package subscription operation.

	Typically these are written to a http.Request.
*/
type AddPackageSubscriptionParams struct {

	// ContentType.
	ContentType *string

	/* Body.

	   Subscription request body
	*/
	Body *models.SubscriptionBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add package subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPackageSubscriptionParams) WithDefaults() *AddPackageSubscriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add package subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPackageSubscriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add package subscription params
func (o *AddPackageSubscriptionParams) WithTimeout(timeout time.Duration) *AddPackageSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add package subscription params
func (o *AddPackageSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add package subscription params
func (o *AddPackageSubscriptionParams) WithContext(ctx context.Context) *AddPackageSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add package subscription params
func (o *AddPackageSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add package subscription params
func (o *AddPackageSubscriptionParams) WithHTTPClient(client *http.Client) *AddPackageSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add package subscription params
func (o *AddPackageSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the add package subscription params
func (o *AddPackageSubscriptionParams) WithContentType(contentType *string) *AddPackageSubscriptionParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the add package subscription params
func (o *AddPackageSubscriptionParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the add package subscription params
func (o *AddPackageSubscriptionParams) WithBody(body *models.SubscriptionBody) *AddPackageSubscriptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add package subscription params
func (o *AddPackageSubscriptionParams) SetBody(body *models.SubscriptionBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddPackageSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
