// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOptOutEntryParams creates a new DeleteOptOutEntryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOptOutEntryParams() *DeleteOptOutEntryParams {
	return &DeleteOptOutEntryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOptOutEntryParamsWithTimeout creates a new DeleteOptOutEntryParams object
// with the ability to set a timeout on a request.
func NewDeleteOptOutEntryParamsWithTimeout(timeout time.Duration) *DeleteOptOutEntryParams {
	return &DeleteOptOutEntryParams{
		timeout: timeout,
	}
}

// NewDeleteOptOutEntryParamsWithContext creates a new DeleteOptOutEntryParams object
// with the ability to set a context for a request.
func NewDeleteOptOutEntryParamsWithContext(ctx context.Context) *DeleteOptOutEntryParams {
	return &DeleteOptOutEntryParams{
		Context: ctx,
	}
}

// NewDeleteOptOutEntryParamsWithHTTPClient creates a new DeleteOptOutEntryParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOptOutEntryParamsWithHTTPClient(client *http.Client) *DeleteOptOutEntryParams {
	return &DeleteOptOutEntryParams{
		HTTPClient: client,
	}
}

/*
DeleteOptOutEntryParams contains all the parameters to send to the API endpoint

	for the delete opt out entry operation.

	Typically these are written to a http.Request.
*/
type DeleteOptOutEntryParams struct {

	/* OptOutID.

	   Opt-out entry ID

	   Format: uuid
	*/
	OptOutID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete opt out entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOptOutEntryParams) WithDefaults() *DeleteOptOutEntryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete opt out entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOptOutEntryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete opt out entry params
func (o *DeleteOptOutEntryParams) WithTimeout(timeout time.Duration) *DeleteOptOutEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete opt out entry params
func (o *DeleteOptOutEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete opt out entry params
func (o *DeleteOptOutEntryParams) WithContext(ctx context.Context) *DeleteOptOutEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete opt out entry params
func (o *DeleteOptOutEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete opt out entry params
func (o *DeleteOptOutEntryParams) WithHTTPClient(client *http.Client) *DeleteOptOutEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete opt out entry params
func (o *DeleteOptOutEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOptOutID adds the optOutID to the delete opt out entry params
func (o *DeleteOptOutEntryParams) WithOptOutID(optOutID strfmt.UUID) *DeleteOptOutEntryParams {
	o.SetOptOutID(optOutID)
	return o
}

// SetOptOutID adds the optOutId to the delete opt out entry params
func (o *DeleteOptOutEntryParams) SetOptOutID(optOutID strfmt.UUID) {
	o.OptOutID = optOutID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOptOutEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param optOutID
	if err := r.SetPathParam("optOutID", o.OptOutID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
