// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePackageSubscriptionParams creates a new DeletePackageSubscriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePackageSubscriptionParams() *DeletePackageSubscriptionParams {
	return &DeletePackageSubscriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePackageSubscriptionParamsWithTimeout creates a new DeletePackageSubscriptionParams object
// with the ability to set a timeout on a request.
func NewDeletePackageSubscriptionParamsWithTimeout(timeout time.Duration) *DeletePackageSubscriptionParams {
	return &DeletePackageSubscriptionParams{
		timeout: timeout,
	}
}

// NewDeletePackageSubscriptionParamsWithContext creates a new DeletePackageSubscriptionParams object
// with the ability to set a context for a request.
func NewDeletePackageSubscriptionParamsWithContext(ctx context.Context) *DeletePackageSubscriptionParams {
	return &DeletePackageSubscriptionParams{
		Context: ctx,
	}
}

// NewDeletePackageSubscriptionParamsWithHTTPClient creates a new DeletePackageSubscriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePackageSubscriptionParamsWithHTTPClient(client *http.Client) *DeletePackageSubscriptionParams {
	return &DeletePackageSubscriptionParams{
		HTTPClient: client,
	}
}

/*
DeletePackageSubscriptionParams contains all the parameters to send to the API endpoint

	for the delete package subscription operation.

	Typically these are written to a http.Request.
*/
type DeletePackageSubscriptionParams struct {

	/* EventKind.

	   Event kind
	*/
	EventKind string

	/* PackageID.

	   Package ID

	   Format: uuid
	*/
	PackageID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete package subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePackageSubscriptionParams) WithDefaults() *DeletePackageSubscriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete package subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePackageSubscriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete package subscription params
func (o *DeletePackageSubscriptionParams) WithTimeout(timeout time.Duration) *DeletePackageSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete package subscription params
func (o *DeletePackageSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete package subscription params
func (o *DeletePackageSubscriptionParams) WithContext(ctx context.Context) *DeletePackageSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete package subscription params
func (o *DeletePackageSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete package subscription params
func (o *DeletePackageSubscriptionParams) WithHTTPClient(client *http.Client) *DeletePackageSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete package subscription params
func (o *DeletePackageSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventKind adds the eventKind to the delete package subscription params
func (o *DeletePackageSubscriptionParams) WithEventKind(eventKind string) *DeletePackageSubscriptionParams {
	o.SetEventKind(eventKind)
	return o
}

// SetEventKind adds the eventKind to the delete package subscription params
func (o *DeletePackageSubscriptionParams) SetEventKind(eventKind string) {
	o.EventKind = eventKind
}

// WithPackageID adds the packageID to the delete package subscription params
func (o *DeletePackageSubscriptionParams) WithPackageID(packageID strfmt.UUID) *DeletePackageSubscriptionParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the delete package subscription params
func (o *DeletePackageSubscriptionParams) SetPackageID(packageID strfmt.UUID) {
	o.PackageID = packageID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePackageSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param event_kind
	qrEventKind := o.EventKind
	qEventKind := qrEventKind
	if qEventKind != "" {

		if err := r.SetQueryParam("event_kind", qEventKind); err != nil {
			return err
		}
	}

	// query param packageID
	qrPackageID := o.PackageID
	qPackageID := qrPackageID.String()
	if qPackageID != "" {

		if err := r.SetQueryParam("packageID", qPackageID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
