// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationProfileParams creates a new GetOrganizationProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationProfileParams() *GetOrganizationProfileParams {
	return &GetOrganizationProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationProfileParamsWithTimeout creates a new GetOrganizationProfileParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationProfileParamsWithTimeout(timeout time.Duration) *GetOrganizationProfileParams {
	return &GetOrganizationProfileParams{
		timeout: timeout,
	}
}

// NewGetOrganizationProfileParamsWithContext creates a new GetOrganizationProfileParams object
// with the ability to set a context for a request.
func NewGetOrganizationProfileParamsWithContext(ctx context.Context) *GetOrganizationProfileParams {
	return &GetOrganizationProfileParams{
		Context: ctx,
	}
}

// NewGetOrganizationProfileParamsWithHTTPClient creates a new GetOrganizationProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationProfileParamsWithHTTPClient(client *http.Client) *GetOrganizationProfileParams {
	return &GetOrganizationProfileParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationProfileParams contains all the parameters to send to the API endpoint

	for the get organization profile operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationProfileParams struct {

	/* OrgName.

	   Organization name
	*/
	OrgName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationProfileParams) WithDefaults() *GetOrganizationProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization profile params
func (o *GetOrganizationProfileParams) WithTimeout(timeout time.Duration) *GetOrganizationProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization profile params
func (o *GetOrganizationProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization profile params
func (o *GetOrganizationProfileParams) WithContext(ctx context.Context) *GetOrganizationProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization profile params
func (o *GetOrganizationProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization profile params
func (o *GetOrganizationProfileParams) WithHTTPClient(client *http.Client) *GetOrganizationProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization profile params
func (o *GetOrganizationProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgName adds the orgName to the get organization profile params
func (o *GetOrganizationProfileParams) WithOrgName(orgName string) *GetOrganizationProfileParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the get organization profile params
func (o *GetOrganizationProfileParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
