// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// NewUpdateOrganizationAuthPolicyParams creates a new UpdateOrganizationAuthPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOrganizationAuthPolicyParams() *UpdateOrganizationAuthPolicyParams {
	return &UpdateOrganizationAuthPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOrganizationAuthPolicyParamsWithTimeout creates a new UpdateOrganizationAuthPolicyParams object
// with the ability to set a timeout on a request.
func NewUpdateOrganizationAuthPolicyParamsWithTimeout(timeout time.Duration) *UpdateOrganizationAuthPolicyParams {
	return &UpdateOrganizationAuthPolicyParams{
		timeout: timeout,
	}
}

// NewUpdateOrganizationAuthPolicyParamsWithContext creates a new UpdateOrganizationAuthPolicyParams object
// with the ability to set a context for a request.
func NewUpdateOrganizationAuthPolicyParamsWithContext(ctx context.Context) *UpdateOrganizationAuthPolicyParams {
	return &UpdateOrganizationAuthPolicyParams{
		Context: ctx,
	}
}

// NewUpdateOrganizationAuthPolicyParamsWithHTTPClient creates a new UpdateOrganizationAuthPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOrganizationAuthPolicyParamsWithHTTPClient(client *http.Client) *UpdateOrganizationAuthPolicyParams {
	return &UpdateOrganizationAuthPolicyParams{
		HTTPClient: client,
	}
}

/*
UpdateOrganizationAuthPolicyParams contains all the parameters to send to the API endpoint

	for the update organization auth policy operation.

	Typically these are written to a http.Request.
*/
type UpdateOrganizationAuthPolicyParams struct {

	// ContentType.
	ContentType *string

	// Body.
	Body *models.AuthorizationPolicy

	/* OrgName.

	   Organization name
	*/
	OrgName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update organization auth policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrganizationAuthPolicyParams) WithDefaults() *UpdateOrganizationAuthPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update organization auth policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrganizationAuthPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithTimeout(timeout time.Duration) *UpdateOrganizationAuthPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithContext(ctx context.Context) *UpdateOrganizationAuthPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithHTTPClient(client *http.Client) *UpdateOrganizationAuthPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithContentType(contentType *string) *UpdateOrganizationAuthPolicyParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithBody(body *models.AuthorizationPolicy) *UpdateOrganizationAuthPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetBody(body *models.AuthorizationPolicy) {
	o.Body = body
}

// WithOrgName adds the orgName to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) WithOrgName(orgName string) *UpdateOrganizationAuthPolicyParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the update organization auth policy params
func (o *UpdateOrganizationAuthPolicyParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOrganizationAuthPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
