// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// ResetPasswordCodeReader is a Reader for the ResetPasswordCode structure.
type ResetPasswordCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResetPasswordCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewResetPasswordCodeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewResetPasswordCodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewResetPasswordCodeTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewResetPasswordCodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewResetPasswordCodeCreated creates a ResetPasswordCodeCreated with default headers values
func NewResetPasswordCodeCreated() *ResetPasswordCodeCreated {
	return &ResetPasswordCodeCreated{}
}

/*
ResetPasswordCodeCreated describes a response with status code 201, with default header values.

The request has succeeded and has led to the creation of a resource
*/
type ResetPasswordCodeCreated struct {
}

// IsSuccess returns true when this reset password code created response has a 2xx status code
func (o *ResetPasswordCodeCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reset password code created response has a 3xx status code
func (o *ResetPasswordCodeCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset password code created response has a 4xx status code
func (o *ResetPasswordCodeCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this reset password code created response has a 5xx status code
func (o *ResetPasswordCodeCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this reset password code created response a status code equal to that given
func (o *ResetPasswordCodeCreated) IsCode(code int) bool {
	return code == 201
}

func (o *ResetPasswordCodeCreated) Error() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeCreated ", 201)
}

func (o *ResetPasswordCodeCreated) String() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeCreated ", 201)
}

func (o *ResetPasswordCodeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResetPasswordCodeBadRequest creates a ResetPasswordCodeBadRequest with default headers values
func NewResetPasswordCodeBadRequest() *ResetPasswordCodeBadRequest {
	return &ResetPasswordCodeBadRequest{}
}

/*
ResetPasswordCodeBadRequest describes a response with status code 400, with default header values.

The request sent was not valid
*/
type ResetPasswordCodeBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this reset password code bad request response has a 2xx status code
func (o *ResetPasswordCodeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reset password code bad request response has a 3xx status code
func (o *ResetPasswordCodeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset password code bad request response has a 4xx status code
func (o *ResetPasswordCodeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this reset password code bad request response has a 5xx status code
func (o *ResetPasswordCodeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this reset password code bad request response a status code equal to that given
func (o *ResetPasswordCodeBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ResetPasswordCodeBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeBadRequest  %+v", 400, o.Payload)
}

func (o *ResetPasswordCodeBadRequest) String() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeBadRequest  %+v", 400, o.Payload)
}

func (o *ResetPasswordCodeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ResetPasswordCodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResetPasswordCodeTooManyRequests creates a ResetPasswordCodeTooManyRequests with default headers values
func NewResetPasswordCodeTooManyRequests() *ResetPasswordCodeTooManyRequests {
	return &ResetPasswordCodeTooManyRequests{}
}

/*
ResetPasswordCodeTooManyRequests describes a response with status code 429, with default header values.

The user has sent too many requests in a given amount of time
*/
type ResetPasswordCodeTooManyRequests struct {
}

// IsSuccess returns true when this reset password code too many requests response has a 2xx status code
func (o *ResetPasswordCodeTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reset password code too many requests response has a 3xx status code
func (o *ResetPasswordCodeTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset password code too many requests response has a 4xx status code
func (o *ResetPasswordCodeTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this reset password code too many requests response has a 5xx status code
func (o *ResetPasswordCodeTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this reset password code too many requests response a status code equal to that given
func (o *ResetPasswordCodeTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *ResetPasswordCodeTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeTooManyRequests ", 429)
}

func (o *ResetPasswordCodeTooManyRequests) String() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeTooManyRequests ", 429)
}

func (o *ResetPasswordCodeTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResetPasswordCodeInternalServerError creates a ResetPasswordCodeInternalServerError with default headers values
func NewResetPasswordCodeInternalServerError() *ResetPasswordCodeInternalServerError {
	return &ResetPasswordCodeInternalServerError{}
}

/*
ResetPasswordCodeInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition that prevented it from fulfilling the request
*/
type ResetPasswordCodeInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this reset password code internal server error response has a 2xx status code
func (o *ResetPasswordCodeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reset password code internal server error response has a 3xx status code
func (o *ResetPasswordCodeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset password code internal server error response has a 4xx status code
func (o *ResetPasswordCodeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this reset password code internal server error response has a 5xx status code
func (o *ResetPasswordCodeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this reset password code internal server error response a status code equal to that given
func (o *ResetPasswordCodeInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ResetPasswordCodeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeInternalServerError  %+v", 500, o.Payload)
}

func (o *ResetPasswordCodeInternalServerError) String() string {
	return fmt.Sprintf("[POST /users/password-reset-code][%d] resetPasswordCodeInternalServerError  %+v", 500, o.Payload)
}

func (o *ResetPasswordCodeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ResetPasswordCodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
