// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/artifacthub-client-go/models"
)

// NewUpdateUserRepositoryParams creates a new UpdateUserRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateUserRepositoryParams() *UpdateUserRepositoryParams {
	return &UpdateUserRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserRepositoryParamsWithTimeout creates a new UpdateUserRepositoryParams object
// with the ability to set a timeout on a request.
func NewUpdateUserRepositoryParamsWithTimeout(timeout time.Duration) *UpdateUserRepositoryParams {
	return &UpdateUserRepositoryParams{
		timeout: timeout,
	}
}

// NewUpdateUserRepositoryParamsWithContext creates a new UpdateUserRepositoryParams object
// with the ability to set a context for a request.
func NewUpdateUserRepositoryParamsWithContext(ctx context.Context) *UpdateUserRepositoryParams {
	return &UpdateUserRepositoryParams{
		Context: ctx,
	}
}

// NewUpdateUserRepositoryParamsWithHTTPClient creates a new UpdateUserRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateUserRepositoryParamsWithHTTPClient(client *http.Client) *UpdateUserRepositoryParams {
	return &UpdateUserRepositoryParams{
		HTTPClient: client,
	}
}

/*
UpdateUserRepositoryParams contains all the parameters to send to the API endpoint

	for the update user repository operation.

	Typically these are written to a http.Request.
*/
type UpdateUserRepositoryParams struct {

	// ContentType.
	ContentType *string

	/* Body.

	   Repository request body
	*/
	Body *models.RepositoryBody

	/* RepoName.

	   Repository name
	*/
	RepoName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update user repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserRepositoryParams) WithDefaults() *UpdateUserRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update user repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update user repository params
func (o *UpdateUserRepositoryParams) WithTimeout(timeout time.Duration) *UpdateUserRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user repository params
func (o *UpdateUserRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user repository params
func (o *UpdateUserRepositoryParams) WithContext(ctx context.Context) *UpdateUserRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user repository params
func (o *UpdateUserRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user repository params
func (o *UpdateUserRepositoryParams) WithHTTPClient(client *http.Client) *UpdateUserRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user repository params
func (o *UpdateUserRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the update user repository params
func (o *UpdateUserRepositoryParams) WithContentType(contentType *string) *UpdateUserRepositoryParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the update user repository params
func (o *UpdateUserRepositoryParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the update user repository params
func (o *UpdateUserRepositoryParams) WithBody(body *models.RepositoryBody) *UpdateUserRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update user repository params
func (o *UpdateUserRepositoryParams) SetBody(body *models.RepositoryBody) {
	o.Body = body
}

// WithRepoName adds the repoName to the update user repository params
func (o *UpdateUserRepositoryParams) WithRepoName(repoName string) *UpdateUserRepositoryParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the update user repository params
func (o *UpdateUserRepositoryParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repoName
	if err := r.SetPathParam("repoName", o.RepoName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
