// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Data8 Data8
//
// swagger:model Data8
type Data8 struct {

	// custom resources definitions
	CustomResourcesDefinitions []*CustomResourcesDefinition `json:"customResourcesDefinitions"`

	// custom resources definitions examples
	// Example: [{\"apiVersion\": v1alpha\n, \"kind\": CustomResource\n, \"spec\": {\n  \"replicas\": 1\n  }\n}}]
	CustomResourcesDefinitionsExamples string `json:"customResourcesDefinitionsExamples,omitempty"`

	// is global operator
	// Required: true
	IsGlobalOperator *bool `json:"isGlobalOperator"`
}

// Validate validates this data8
func (m *Data8) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomResourcesDefinitions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsGlobalOperator(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Data8) validateCustomResourcesDefinitions(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomResourcesDefinitions) { // not required
		return nil
	}

	for i := 0; i < len(m.CustomResourcesDefinitions); i++ {
		if swag.IsZero(m.CustomResourcesDefinitions[i]) { // not required
			continue
		}

		if m.CustomResourcesDefinitions[i] != nil {
			if err := m.CustomResourcesDefinitions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customResourcesDefinitions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("customResourcesDefinitions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Data8) validateIsGlobalOperator(formats strfmt.Registry) error {

	if err := validate.Required("isGlobalOperator", "body", m.IsGlobalOperator); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this data8 based on the context it is used
func (m *Data8) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomResourcesDefinitions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Data8) contextValidateCustomResourcesDefinitions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CustomResourcesDefinitions); i++ {

		if m.CustomResourcesDefinitions[i] != nil {
			if err := m.CustomResourcesDefinitions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customResourcesDefinitions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("customResourcesDefinitions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Data8) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Data8) UnmarshalBinary(b []byte) error {
	var res Data8
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
