// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Maintainer Maintainer
//
// swagger:model Maintainer
type Maintainer struct {

	// email
	// Example: maintainer@email.com
	// Required: true
	Email *string `json:"email"`

	// maintainer id
	// Format: uuid
	MaintainerID strfmt.UUID `json:"maintainer_id,omitempty"`

	// name
	// Example: maintainer1
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this maintainer
func (m *Maintainer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaintainerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Maintainer) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *Maintainer) validateMaintainerID(formats strfmt.Registry) error {
	if swag.IsZero(m.MaintainerID) { // not required
		return nil
	}

	if err := validate.FormatOf("maintainer_id", "body", "uuid", m.MaintainerID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Maintainer) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this maintainer based on context it is used
func (m *Maintainer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Maintainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Maintainer) UnmarshalBinary(b []byte) error {
	var res Maintainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
