// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscriptionsOptOutResponse SubscriptionsOptOutResponse
//
// swagger:model SubscriptionsOptOutResponse
type SubscriptionsOptOutResponse struct {

	// event kind
	// Required: true
	EventKind *EventKindID `json:"event_kind"`

	// opt out id
	// Required: true
	// Format: uuid
	OptOutID *strfmt.UUID `json:"opt_out_id"`

	// repository
	// Required: true
	Repository *RepositorySummary `json:"repository"`
}

// Validate validates this subscriptions opt out response
func (m *SubscriptionsOptOutResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOptOutID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepository(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscriptionsOptOutResponse) validateEventKind(formats strfmt.Registry) error {

	if err := validate.Required("event_kind", "body", m.EventKind); err != nil {
		return err
	}

	if err := validate.Required("event_kind", "body", m.EventKind); err != nil {
		return err
	}

	if m.EventKind != nil {
		if err := m.EventKind.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event_kind")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event_kind")
			}
			return err
		}
	}

	return nil
}

func (m *SubscriptionsOptOutResponse) validateOptOutID(formats strfmt.Registry) error {

	if err := validate.Required("opt_out_id", "body", m.OptOutID); err != nil {
		return err
	}

	if err := validate.FormatOf("opt_out_id", "body", "uuid", m.OptOutID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SubscriptionsOptOutResponse) validateRepository(formats strfmt.Registry) error {

	if err := validate.Required("repository", "body", m.Repository); err != nil {
		return err
	}

	if m.Repository != nil {
		if err := m.Repository.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("repository")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("repository")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this subscriptions opt out response based on the context it is used
func (m *SubscriptionsOptOutResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEventKind(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRepository(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscriptionsOptOutResponse) contextValidateEventKind(ctx context.Context, formats strfmt.Registry) error {

	if m.EventKind != nil {
		if err := m.EventKind.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event_kind")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event_kind")
			}
			return err
		}
	}

	return nil
}

func (m *SubscriptionsOptOutResponse) contextValidateRepository(ctx context.Context, formats strfmt.Registry) error {

	if m.Repository != nil {
		if err := m.Repository.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("repository")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("repository")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionsOptOutResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionsOptOutResponse) UnmarshalBinary(b []byte) error {
	var res SubscriptionsOptOutResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
